// Curriculum data. Transliteration uses the common learner scheme:
// apostrophe marks ejectives (k' p' t' ts' ch' q'), kh/gh/zh/sh/ch/ts/dz digraphs.
// Russian speakers see Cyrillic pronunciation generated from the Georgian (see i18n.js).

// [letter, latin, sound (English), sound (Russian)]
const ALPHABET = [
  ['ა', 'a', 'a in "father"', '«а» как в «мама»'],
  ['ბ', 'b', 'b', '«б»'],
  ['გ', 'g', 'g in "go"', '«г»'],
  ['დ', 'd', 'd', '«д»'],
  ['ე', 'e', 'e in "pet"', '«э» как в «это»'],
  ['ვ', 'v', 'v', '«в»'],
  ['ზ', 'z', 'z', '«з»'],
  ['თ', 't', 'aspirated t', '«т» с выдохом'],
  ['ი', 'i', 'ee in "see"', '«и»'],
  ['კ', "k'", 'ejective k (no puff of air)', 'смычное «к» (без выдоха)'],
  ['ლ', 'l', 'l', '«л»'],
  ['მ', 'm', 'm', '«м»'],
  ['ნ', 'n', 'n', '«н»'],
  ['ო', 'o', 'o in "more"', '«о»'],
  ['პ', "p'", 'ejective p', 'смычное «п»'],
  ['ჟ', 'zh', 's in "measure"', '«ж»'],
  ['რ', 'r', 'rolled r', 'раскатистое «р»'],
  ['ს', 's', 's', '«с»'],
  ['ტ', "t'", 'ejective t', 'смычное «т»'],
  ['უ', 'u', 'oo in "boot"', '«у»'],
  ['ფ', 'p', 'aspirated p', '«п» с выдохом'],
  ['ქ', 'k', 'aspirated k', '«к» с выдохом'],
  ['ღ', 'gh', 'French r, voiced in the throat', 'как французское «r», звонкое, в горле'],
  ['ყ', "q'", 'ejective q, deep in the throat', 'смычное «к» глубоко в горле'],
  ['შ', 'sh', 'sh', '«ш»'],
  ['ჩ', 'ch', 'aspirated ch', '«ч» с выдохом'],
  ['ც', 'ts', 'ts in "cats"', '«ц»'],
  ['ძ', 'dz', 'ds in "kids"', 'звонкое «дз»'],
  ['წ', "ts'", 'ejective ts', 'смычное «ц»'],
  ['ჭ', "ch'", 'ejective ch', 'смычное «ч»'],
  ['ხ', 'kh', 'ch in Scottish "loch"', '«х»'],
  ['ჯ', 'j', 'j in "jam"', '«дж»'],
  ['ჰ', 'h', 'h', 'лёгкое «х», как английское h'],
];

// Each word: [georgian, transliteration, english, russian, note (en)?, note (ru)?]
const LESSONS = [
  {
    id: 'greetings', title: 'Greetings & basics', titleRu: 'Приветствия', icon: 'hand',
    words: [
      ['გამარჯობა', 'gamarjoba', 'hello', 'привет'],
      ['ნახვამდის', 'nakhvamdis', 'goodbye', 'до свидания'],
      ['მადლობა', 'madloba', 'thank you', 'спасибо'],
      ['გთხოვთ', 'gtkhovt', 'please', 'пожалуйста', 'formal', 'вежливо'],
      ['კი', "k'i", 'yes', 'да', 'casual', 'разговорное'],
      ['დიახ', 'diakh', 'yes', 'да', 'polite', 'вежливо'],
      ['არა', 'ara', 'no', 'нет'],
      ['ბოდიში', 'bodishi', 'sorry / excuse me', 'извините / простите'],
      ['როგორ ხარ?', 'rogor khar?', 'how are you?', 'как дела?'],
      ['კარგად', "k'argad", 'well / fine', 'хорошо'],
      ['დილა მშვიდობისა', 'dila mshvidobisa', 'good morning', 'доброе утро'],
      ['ღამე მშვიდობისა', 'ghame mshvidobisa', 'good night', 'спокойной ночи'],
    ],
  },
  {
    id: 'numbers', title: 'Numbers', titleRu: 'Числа', icon: 'hash',
    words: [
      ['ერთი', 'erti', 'one', 'один'], ['ორი', 'ori', 'two', 'два'], ['სამი', 'sami', 'three', 'три'],
      ['ოთხი', 'otkhi', 'four', 'четыре'], ['ხუთი', 'khuti', 'five', 'пять'], ['ექვსი', 'ekvsi', 'six', 'шесть'],
      ['შვიდი', 'shvidi', 'seven', 'семь'], ['რვა', 'rva', 'eight', 'восемь'], ['ცხრა', 'tskhra', 'nine', 'девять'],
      ['ათი', 'ati', 'ten', 'десять'],
      ['ოცი', 'otsi', 'twenty', 'двадцать', 'Georgian counts in twenties!', 'в грузинском счёт идёт двадцатками!'],
      ['ასი', 'asi', 'one hundred', 'сто'],
    ],
  },
  {
    id: 'food', title: 'Food & drink', titleRu: 'Еда и напитки', icon: 'utensils',
    words: [
      ['პური', "p'uri", 'bread', 'хлеб'], ['წყალი', "ts'q'ali", 'water', 'вода'], ['ღვინო', 'ghvino', 'wine', 'вино'],
      ['ყველი', "q'veli", 'cheese', 'сыр'],
      ['ხაჭაპური', "khach'ap'uri", 'khachapuri (cheese bread)', 'хачапури (хлеб с сыром)'],
      ['ხინკალი', "khink'ali", 'khinkali (dumplings)', 'хинкали'],
      ['ჩაი', 'chai', 'tea', 'чай'], ['ყავა', "q'ava", 'coffee', 'кофе'], ['ხორცი', 'khortsi', 'meat', 'мясо'],
      ['ვაშლი', 'vashli', 'apple', 'яблоко'], ['რძე', 'rdze', 'milk', 'молоко'],
      ['გემრიელია', 'gemrielia', "it's delicious", 'вкусно'],
    ],
  },
  {
    id: 'family', title: 'Family & people', titleRu: 'Семья и люди', icon: 'users',
    words: [
      ['დედა', 'deda', 'mother', 'мама', 'yes, "deda" means mom!', 'да, «деда» - это мама!'],
      ['მამა', 'mama', 'father', 'папа', 'and "mama" means dad', 'а «мама» - это папа'],
      ['ძმა', 'dzma', 'brother', 'брат'],
      ['და', 'da', 'sister', 'сестра', 'also means "and"', 'также значит «и»'],
      ['შვილი', 'shvili', 'child (son/daughter)', 'ребёнок (сын/дочь)'],
      ['ბებია', 'bebia', 'grandmother', 'бабушка'], ['ბაბუა', 'babua', 'grandfather', 'дедушка'],
      ['მეგობარი', 'megobari', 'friend', 'друг'], ['ოჯახი', 'ojakhi', 'family', 'семья'],
      ['კაცი', "k'atsi", 'man', 'мужчина'], ['ქალი', 'kali', 'woman', 'женщина'],
    ],
  },
  {
    id: 'everyday', title: 'Everyday words', titleRu: 'Повседневные слова', icon: 'house',
    words: [
      ['სახლი', 'sakhli', 'house', 'дом'], ['ქალაქი', 'kalaki', 'city', 'город'], ['წიგნი', "ts'igni", 'book', 'книга'],
      ['კატა', "k'at'a", 'cat', 'кошка'], ['ძაღლი', 'dzaghli', 'dog', 'собака'], ['დღე', 'dghe', 'day', 'день'],
      ['ღამე', 'ghame', 'night', 'ночь'], ['დღეს', 'dghes', 'today', 'сегодня'], ['ხვალ', 'khval', 'tomorrow', 'завтра'],
      ['გუშინ', 'gushin', 'yesterday', 'вчера'], ['კარგი', "k'argi", 'good', 'хороший'], ['ცუდი', 'tsudi', 'bad', 'плохой'],
      ['დიდი', 'didi', 'big', 'большой'], ['პატარა', "p'at'ara", 'small', 'маленький'], ['ლამაზი', 'lamazi', 'beautiful', 'красивый'],
    ],
  },
  {
    id: 'phrases', title: 'Useful phrases', titleRu: 'Полезные фразы', icon: 'message-circle',
    words: [
      ['მე მქვია…', 'me mkvia…', 'my name is…', 'меня зовут…'],
      ['არ მესმის', 'ar mesmis', "I don't understand", 'я не понимаю'],
      ['ინგლისურად ლაპარაკობთ?', "inglisurad lap'arak'obt?", 'do you speak English?', 'вы говорите по-английски?'],
      ['რუსულად ლაპარაკობთ?', "rusulad lap'arak'obt?", 'do you speak Russian?', 'вы говорите по-русски?'],
      ['რა ღირს?', 'ra ghirs?', 'how much is it?', 'сколько стоит?'],
      ['სად არის…?', 'sad aris…?', 'where is…?', 'где…?'],
      ['ძალიან კარგი', "dzalian k'argi", 'very good', 'очень хорошо'],
      ['გაუმარჯოს!', 'gaumarjos!', 'cheers!', 'за здоровье!'],
      ['მიყვარხარ', "miq'varkhar", 'I love you', 'я тебя люблю'],
      ['ნელა, გთხოვთ', 'nela, gtkhovt', 'slowly, please', 'медленнее, пожалуйста'],
    ],
  },
  {
    id: 'verbs', title: 'Common verbs', titleRu: 'Частые глаголы', icon: 'person-standing',
    intro: 'Georgian verbs change a lot by person. These are the everyday "I" forms - learn them as phrases.',
    introRu: 'Грузинские глаголы сильно меняются по лицам. Здесь повседневные формы «я» - учи их как фразы.',
    words: [
      ['ვარ', 'var', 'I am', 'я есть'],
      ['მინდა', 'minda', 'I want', 'я хочу'],
      ['მაქვს', 'makvs', 'I have', 'у меня есть', 'for things', 'для вещей'],
      ['ვიცი', 'vitsi', 'I know', 'я знаю'],
      ['მესმის', 'mesmis', 'I understand / I hear', 'я понимаю / я слышу'],
      ['მომწონს', "momts'ons", 'I like (it)', 'мне нравится'],
      ['მიყვარს', "miq'vars", 'I love (it)', 'я люблю (это)'],
      ['ვჭამ', "vch'am", 'I eat', 'я ем'],
      ['ვსვამ', 'vsvam', 'I drink', 'я пью'],
      ['მივდივარ', 'mivdivar', 'I am going', 'я иду'],
      ['ვლაპარაკობ', "vlap'arak'ob", 'I speak', 'я говорю'],
      ['ვცხოვრობ', 'vtskhovrob', 'I live', 'я живу'],
      ['ვმუშაობ', 'vmushaob', 'I work', 'я работаю'],
      ['ვსწავლობ', "vsts'avlob", 'I study / I learn', 'я учусь'],
    ],
  },
  {
    id: 'days', title: 'Days of the week', titleRu: 'Дни недели', icon: 'calendar-days',
    intro: 'Monday to Thursday are "two, three, four, five" + შაბათი (shabati, Saturday).',
    introRu: 'Понедельник–четверг - это «два, три, четыре, пять» + შაბათი (шабати, суббота).',
    words: [
      ['ორშაბათი', 'orshabati', 'Monday', 'понедельник'],
      ['სამშაბათი', 'samshabati', 'Tuesday', 'вторник'],
      ['ოთხშაბათი', 'otkhshabati', 'Wednesday', 'среда'],
      ['ხუთშაბათი', 'khutshabati', 'Thursday', 'четверг'],
      ['პარასკევი', "p'arask'evi", 'Friday', 'пятница'],
      ['შაბათი', 'shabati', 'Saturday', 'суббота'],
      ['კვირა', "k'vira", 'Sunday', 'воскресенье', 'also means "week"', 'также значит «неделя»'],
    ],
  },
  {
    id: 'months', title: 'Months', titleRu: 'Месяцы', icon: 'calendar',
    words: [
      ['იანვარი', 'ianvari', 'January', 'январь'],
      ['თებერვალი', 'tebervali', 'February', 'февраль'],
      ['მარტი', "mart'i", 'March', 'март'],
      ['აპრილი', "ap'rili", 'April', 'апрель'],
      ['მაისი', 'maisi', 'May', 'май'],
      ['ივნისი', 'ivnisi', 'June', 'июнь'],
      ['ივლისი', 'ivlisi', 'July', 'июль'],
      ['აგვისტო', "agvist'o", 'August', 'август'],
      ['სექტემბერი', "sekt'emberi", 'September', 'сентябрь'],
      ['ოქტომბერი', "okt'omberi", 'October', 'октябрь'],
      ['ნოემბერი', 'noemberi', 'November', 'ноябрь'],
      ['დეკემბერი', "dek'emberi", 'December', 'декабрь'],
    ],
  },
  {
    id: 'colours', title: 'Colours', titleRu: 'Цвета', icon: 'palette',
    words: [
      ['წითელი', "ts'iteli", 'red', 'красный'],
      ['ლურჯი', 'lurji', 'blue', 'синий'],
      ['ცისფერი', 'tsisperi', 'light blue', 'голубой', 'literally "sky-coloured"', 'буквально «цвета неба»'],
      ['მწვანე', "mts'vane", 'green', 'зелёный'],
      ['ყვითელი', "q'viteli", 'yellow', 'жёлтый'],
      ['შავი', 'shavi', 'black', 'чёрный'],
      ['თეთრი', 'tetri', 'white', 'белый'],
      ['ნაცრისფერი', 'natsrisperi', 'grey', 'серый', 'literally "ash-coloured"', 'буквально «цвета пепла»'],
      ['ყავისფერი', "q'avisperi", 'brown', 'коричневый', 'literally "coffee-coloured"', 'буквально «цвета кофе»'],
      ['ვარდისფერი', 'vardisperi', 'pink', 'розовый', 'literally "rose-coloured"', 'буквально «цвета розы»'],
      ['ნარინჯისფერი', 'narinjisperi', 'orange', 'оранжевый'],
      ['იისფერი', 'iisperi', 'purple', 'фиолетовый', 'literally "violet-coloured"', 'буквально «цвета фиалки»'],
    ],
  },
  {
    id: 'travel', title: 'Travel', titleRu: 'Путешествия', icon: 'plane',
    words: [
      ['აეროპორტი', "aerop'ort'i", 'airport', 'аэропорт'],
      ['სადგური', 'sadguri', 'station', 'вокзал / станция'],
      ['ავტობუსი', "avt'obusi", 'bus', 'автобус'],
      ['მატარებელი', "mat'arebeli", 'train', 'поезд'],
      ['ტაქსი', "t'aksi", 'taxi', 'такси'],
      ['სასტუმრო', "sast'umro", 'hotel', 'гостиница'],
      ['ბილეთი', 'bileti', 'ticket', 'билет'],
      ['პასპორტი', "p'asp'ort'i", 'passport', 'паспорт'],
      ['ფული', 'puli', 'money', 'деньги'],
      ['რესტორანი', "rest'orani", 'restaurant', 'ресторан'],
      ['ერთი ბილეთი, გთხოვთ', 'erti bileti, gtkhovt', 'one ticket, please', 'один билет, пожалуйста'],
      ['ანგარიში მომიტანეთ, გთხოვთ', "angarishi momit'anet, gtkhovt", 'bring me the bill, please', 'принесите счёт, пожалуйста',
        'ანგარიში also means "account" or "report"', 'ანგარიში также значит «счёт в банке» или «отчёт»'],
    ],
  },
  {
    id: 'directions', title: 'Asking directions', titleRu: 'Как спросить дорогу', icon: 'signpost',
    words: [
      ['სად არის ტუალეტი?', "sad aris t'ualet'i?", 'where is the toilet?', 'где туалет?'],
      ['შორს არის?', 'shors aris?', 'is it far?', 'это далеко?'],
      ['მარჯვნივ', 'marjvniv', 'to the right', 'направо'],
      ['მარცხნივ', 'martskhniv', 'to the left', 'налево'],
      ['პირდაპირ', "p'irdap'ir", 'straight ahead', 'прямо'],
      ['ახლოს', 'akhlos', 'near', 'близко'],
      ['შორს', 'shors', 'far', 'далеко'],
      ['აქ', 'ak', 'here', 'здесь'],
      ['იქ', 'ik', 'there', 'там'],
      ['ქუჩა', 'kucha', 'street', 'улица'],
      ['რუკა', "ruk'a", 'map', 'карта'],
      ['გაჩერება', 'gachereba', 'bus stop', 'остановка'],
    ],
  },
];

const ALL_WORDS = LESSONS.flatMap(l => l.words.map(w => ({
  ka: w[0], tr: w[1], en: w[2], ru: w[3], note: w[4] || '', noteRu: w[5] || '', lesson: l.id,
})));
